import { Projects, Skills } from "@/interfaces/projects";
import {
  Code,
  TrendingUp,
  ShoppingCart,
  Gamepad2,
  Zap,
  Shield,
} from "lucide-react";

export const ECOMMERCE_PROJECTS: Projects = [
  {
    name: "Palami.com",
    role: "palami_role",
    company: "palami_company",
    period: "palami_period",
    status: "palami_status",
    description: "palami_desc",
    achievements: ["achievement_palami_1", "achievement_palami_2"],
    technologies: ["Shopify", "Liquid", "JavaScript", "CSS3", "HTML5"],
    link: "https://palami.com/",
    impact: "High",
  },
  {
    name: "BuySellVouchers.com",
    role: "buysellvouchers_role",
    company: "buysellvouchers_company",
    period: "buysellvouchers_period",
    status: "buysellvouchers_status",
    description: "buysellvouchers_desc",
    achievements: [
      "achievement_bsv_1",
      "achievement_bsv_3",
      "achievement_bsv_4",
      "achievement_bsv_5",
    ],
    technologies: [
      "Next.js 15",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Strapi CMS",
      "Docker",
    ],
    link: "https://www.buysellvouchers.com/",
    impact: "High",
  },
];

export const ECOMMERCE_SKILLS: Skills = [
  {
    category: "skill_frontend_technologies",
    items: [
      "Next.js 15",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "JavaScript ES6+",
      "CI/CD Pipelines",
    ],
    icon: <Code className="w-5 h-5" />,
  },
  {
    category: "skill_ecommerce_platforms",
    items: ["Shopify", "Custom E-commerce Solutions", "B2B Platforms"],
    icon: <ShoppingCart className="w-5 h-5" />,
  },
  {
    category: "skill_performance_seo",
    items: [
      "Server-Side Rendering",
      "Core Web Vitals Optimization",
      "SEO Enhancement",
      "Performance Auditing",
    ],
    icon: <TrendingUp className="w-5 h-5" />,
  },
];

export const IGAMING_PROJECTS: Projects = [
  {
    name: "Pledoo Casino",
    role: "pledoo_role",
    company: "pledoo_company",
    period: "pledoo_period",
    status: "pledoo_status",
    description: "pledoo_desc",
    achievements: [
      "achievement_pledoo_1",
      "achievement_pledoo_2",
      "achievement_pledoo_3",
    ],
    technologies: [
      "Angular",
      "TypeScript",
      "RxJS",
      "Keystone CMS",
      "RESTful APIs",
      "SCSS",
    ],
    link: "https://pledoo.com/",
    impact: "Medium",
  },
  {
    name: "Royspins Casino",
    role: "royspins_role",
    company: "royspins_company",
    period: "royspins_period",
    status: "royspins_status",
    description: "royspins_desc",
    achievements: [
      "achievement_royspins_1",
      "achievement_royspins_2",
      "achievement_royspins_3",
      "achievement_royspins_4",
      "achievement_royspins_5",
    ],
    technologies: [
      "Angular",
      "TypeScript",
      "RxJS",
      "Socket.IO",
      "Keystone CMS",
      "Payment Integration APIs",
      "Dynamic Form Generation",
    ],
    link: "https://royspins.com/",
    impact: "High",
  },
  {
    name: "Wazbee Casino",
    role: "wazbee_role",
    company: "wazbee_company",
    period: "wazbee_period",
    status: "wazbee_status",
    description: "wazbee_desc",
    achievements: [
      "achievement_wazbee_1",
      "achievement_wazbee_2",
      "achievement_wazbee_3",
      "achievement_wazbee_4",
      "achievement_wazbee_5",
    ],
    technologies: [
      "Angular",
      "TypeScript",
      "RxJS",
      "Socket.IO",
      "Keystone CMS",
      "Payment Integration APIs",
      "Dynamic Form Generation",
    ],
    link: "https://wazbee.casino/",
    impact: "High",
  },
  {
    name: "Welle Casino",
    role: "welle_role",
    company: "welle_company",
    period: "welle_period",
    status: "welle_status",
    description: "welle_desc",
    achievements: [
      "achievement_welle_1",
      "achievement_welle_2",
      "achievement_welle_3",
      "achievement_welle_4",
      "achievement_welle_5",
    ],
    technologies: [
      "Angular",
      "TypeScript",
      "RxJS",
      "Socket.IO",
      "Keystone CMS",
      "Multi-step Forms",
      "Payment Integration APIs",
    ],
    link: "https://welle.casino/",
    impact: "High",
  },
];

export const IGAMING_SKILLS: Skills = [
  {
    category: "skill_angular_technologies",
    items: [
      "Angular",
      "TypeScript",
      "RxJS",
      "Angular CLI",
      "Angular Services & Dependency Injection",
    ],
    icon: <Gamepad2 className="w-5 h-5" />,
  },
  {
    category: "skill_dynamic_ui",
    items: [
      "Dynamic Form Generation",
      "Multi-step Registration",
      "Complex Component Architecture",
      "Responsive UI Design",
      "Interactive Gaming Elements",
    ],
    icon: <Zap className="w-5 h-5" />,
  },
  {
    category: "skill_cms_integration",
    items: [
      "Keystone CMS",
      "Socket.IO Integration",
      "Payment Gateway Integration",
      "Real-time Communication",
      "Performance Optimization",
      "Sumsub Integration",
    ],
    icon: <Shield className="w-5 h-5" />,
  },
];
